#!/usr/bin/env bash
# update and install nginx silently using -y flag

sudo apt-get -y update
sudo apt-get install -y nginx

# Cofigure nginx to listen to port 80 and then  return Hello World! at the root

sudo service nginx start

sudo ufw allow 'Nginx HTTP'
# Give the user ownership to website files for easy editing
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www


echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

# Configure nginx to redirect /redirect_me to another page with a "301 Moved Permanently" status
sed -i 's/server_name _;/server_name _;\n\trewrite \/redirect_me https:\/\/www.youtube.com\/watch\?v=QH2-TGUlwu4 permanent;/' /etc/nginx/sites-enabled/default

# Restart the nginx server
sudo service nginx restart
echo -e "Nginx server is now running and listening on port 80\n"