#!/usr/bin/env bash
# update and install nginx silently using -y flag

sudo apt-get -y update
sudo apt-get install -y nginx

# Cofigure nginx to listen to port 80 and then  return Hello World! at the root

sudo ufw allow 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

sudo sed -i '/^}$/i \ \n\tlocation \/redirect_me {return 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;}' /etc/nginx/sites-available/default


# Restart the nginx server
sudo service nginx restart