#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)
sudo apt-get update
sudo apt-get install -y nginx

# Cofigure nginx to listen to port 80 and then return Hello World! at the root

sudo ufw allow 'Nginx HTTP'

# change permissions to allow us to easily create files in this directory
sudo chmod -R 755 /var/www
# return Hello World! at the root
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

# Configure nginx to redirect /redirect_me to another page with a "301 Moved Permanently" status
sudo sed -i 's/server_name _;/server_name _;\n\trewrite \/redirect_me https:\/\/www.youtube.com\/watch\?v=QH2-TGUlwu4 permanent;/' /etc/nginx/sites-enabled/default

# code to configure redirect for 404 error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
# code to configure redirect for a single page(/redirect_me) and add header to display hostname
string_for_replacement="server_name _;\n\tadd_header X-Served-By \$hostname;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# code to configure redirect for 404 error page
string_for_replacement="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# restart the web server after updating the settings
sudo service nginx restart
