#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server

sudo apt-get -y update
sudo apt-get install -y haproxy

# edit config file
echo "
frontend diana-frontend
        bind *:80
        mode http
        default_backend diana-backend

backend diana-backend
        balance roundrobin
        server 500134-web-01 54.237.118.67:80 check
        server 500134-web-02 52.91.146.16:80 check
" >> /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo service haproxy restart