#!/usr/bin/env bash
# This script fixes the issue of nginx not running at port 80
rm -f /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx start
