#!/usr/bin/env bash
# script that displays ininity with sleep in between and print another string
trap 'echo "I am invincible!!!"' SIGTERM
while :
do
    echo "To infinity and beyond"
    sleep 2
done
