#!/usr/bin/env bash
# Bash script that displays numbers from 1 to 20 and strings
counter=0
while ((counter++<20)); do
    echo $counter
    case $counter in
        4) echo "bad luck from China";;
        9) echo "bad luck from Japan";;
        17) echo "bad luck from Italy";;
    esac
done
