#!/usr/bin/env bash
# This script that displays the time for 12 hours and 59 minutes
hour=-1
minute=1
while ((hour++<12)); do
    echo "Hour: $hour"
    minute=0
    while ((minute++<59)); do
    echo $minute
    done
done
