#!/usr/bin/env bash
# Bash script that configures an Ubuntu server with the below requirements
sudo cp /etc/hosts ~/hosts.copy
sed -i 's/127.0.0.1/127.0.0.2/' ~/hosts.copy
sed -i '1s/^/8.8.8.8 facebook.com\n/' ~/hosts.copy
sudo cp -f ~/hosts.copy /etc/hosts
